### ISSUE TITLE
Missing IDs

### ISSUE THREAD

**Issue by bryc** [jeltaqq/Xbox-Original-GameList#1]
There's probably more but I came across these:
`0x47560009`, `WWII Combat`, *World War II Combat: Road to Berlin*
`0x5553005C`, `Darkwatch`, *Darkwatch*
`0x5451000C`, `CircusMaximus`, *Circus Maximus: Chariot Wars*
`0x41430022`, `The Red Star`, *The Red Star*
`0x4D530050`, `Kameo`, *Kameo: Elements of Power*

**Comment by jeltaqq** [comment]
Thanks for the IDs. Add them.
