### ISSUE TITLE
GTA: SA TitleID error

### ISSUE THREAD

**Issue by kaosengr** [jeltaqq/Xbox-Original-GameList#3]
The TitleID for Grand Theft Auto: San Andreas in your list, 0x545400A3, does not match what I have found for either the NTSC or PAL version of the game.  Each game has its own TitleID:

- NTSC/US - 54540082, and 
- PAL/UK - 54540086.

**Comment by jeltaqq** [comment]
Updated the game list.
0x545400A3 matched the TitleID of the trilogy version.
